name: run-cargo-test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest-16-core
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: ./scripts/task.sh prover-service install-deps 
      - run: cargo fmt --check && cargo xclippy
  rust:
    name: Run cargo test
    runs-on: ubuntu-latest-16-core
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: echo "" > ~/.bashrc
      - run: ./scripts/task.sh setup-dev-environment
      - run: source ~/.bashrc && cargo test 
  rust-macos:
    name: Run cargo test on macos
    runs-on: macos-latest-xlarge
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: echo "" > ~/.bashrc
      - run: ./scripts/task.sh setup-dev-environment
      - run: source ~/.bashrc && cargo test
